[project]
name = "nlp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ipykernel>=7.1.0",
    "nltk>=3.9.2",
    "spacy>=3.8.11",
    "transformers>=4.57.3",
]
